version: '3.8'

services:
  web:
    build: .
    command: gunicorn --workers=8 --threads=4 --bind 0.0.0.0:8000 config.wsgi:application
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data:
  redis_data: