# Generated by Django 5.1.6 on 2025-04-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='Hot Mahsulotmi?'),
        ),
    ]
