# Generated by Django 5.1.6 on 2025-05-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinemarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
